### ISSUE TITLE
iMac OSX (10.10.5): AlethOne pool ming issue

### ISSUE THREAD

**Issue by More-decentral** [ethereum/alethzero#116]
Tried to run pool mining, but the status remains as "waiting" for a long time.

![screen shot 2015-12-29 at 10 00 46 am](https://cloud.githubusercontent.com/assets/16477843/12036424/dcca8a3e-ae13-11e5-93bc-dda22a6fc482.png)

**Comment by enriquefynn** [comment]
You have to select the Pool URL.
127.0.0.1 is yourself

**Comment by chriseth** [comment]
Please re-open if this is not fixed.
