### ISSUE TITLE
Alethzero freezes up when using private chain

### ISSUE THREAD

**Issue by dangup** [ethereum/alethzero#117]
Using OS X El Capitan ver 10.11.2. Unable to proceed on creating my first Dapp. Is this release compatible with this Mac version?

**Comment by CrackerHax** [comment]
Same here on Windows 10. Endless loop opening and closing db when creating the chain, then killed it and restarted. Now it does an endless loop opening and closing db and no gui. Deleting ~\AppData\Local\AlethZero seems to have gotten it to start with GUI.

**Comment by bobsummerwill** [comment]
Closed issue, because [AlethZero is no longer supported](https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/), so this issue will never be addressed.
