### ISSUE TITLE
AlethOne crashes when pool master don't accept the solution submitted

### ISSUE THREAD

**Issue by ramvi** [ethereum/alethzero#121]
In pool mode, AlethOne crashes when the pool master don't accept the solution submitted e.g. the pool difficulty has changed or the submission is too late. This is at least my guess for the reason - it can be something else all together.

AlethOne terminal says:

```
Solution found; submitting to [pool url]
nonce x
mixhash x
header x
seedhash x
target x
ethash x
:( Couldn't submit JSONRPC connectivity problem.
Cannot queue arguments of type eth::EthashProofOfWork::Solution
Make sure eth ethashproofofwork::solution is registrered using qregistermetatype()
```

or

```
QObject::connect: Cannot queue arguments of type 'eth::EthashProofOfWork::WorkPackage'
Make sure 'eth::EthashProofOfWork::WorkPackage' is registered using qRegisterMetaType().
```

VS2013 says about the crash: `Unhandled exception at  (ntdll.dll): A heap has been corrupted`

**Comment by ramvi** [comment]
I guess the error should be `Make sure '...' is registered using **Q_DECLARE_METATYPE()**`, which both of them are in `libaleth\Slave.h`:

``` c++
Q_DECLARE_METATYPE(dev::eth::EthashProofOfWork::Solution)
Q_DECLARE_METATYPE(dev::eth::EthashProofOfWork::WorkPackage)
```

**Comment by chriseth** [comment]
Might be fixed by https://github.com/ethereum/libethereum/pull/163

**Comment by ramvi** [comment]
It still crashes with v 1.1.3 and built from develop. What's weird is that isn't AlethOne using the exact same code as ethminer? If I connect ethminer to the same pool, it doesn't crash. Only AlethOne

**Comment by chriseth** [comment]
Might be fixed by https://github.com/ethereum/alethzero/pull/128

**Comment by bobsummerwill** [comment]
Closed issue, because [AlethZero is no longer supported](https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/), so this issue will never be addressed.
