### ISSUE TITLE
AlethOne not utilizing GPU when mining

### ISSUE THREAD

**Issue by bumski** [ethereum/alethzero#141]
I have a GTX 760, operate on Windows 10 and have an i5-3570 CPU.  When I boot up AlethOne, it only utilizes my CPU and will not use my GPU regardless of what I try.  How can I get this to use my GPU?

**Comment by bobsummerwill** [comment]
Hey @bumski!

How did you set up your AlethOne?   Did you build from source, or use a released version?   Which version?    Do you just start the executable?

There might be command-line options which you are missing.    Others would know better than me, but worth a try to investigate that.

Might also be worth trying "ethminer" on the command-line, and seeing if there is any useful debug output there.

**Comment by bumski** [comment]
Thanks for your response.   I downloaded the most recent version and just
fired up the executable.  Pretty sure I tried the command line before  but
I'll give it a shot soon as I return home again and report back.

**Comment by bobsummerwill** [comment]
No problem.

I have seen many posts about specific graphics cards working or not working, so this stuff is probably all a bit "tweaky".

Looks like it only has 2Gb of memory (http://www.geforce.com/hardware/desktop-gpus/geforce-gtx-760/specifications), which I _think_ might not be enough, so perhaps it is detected, but rejected.   We should be able to get some info in the log, I hope :-)

**Comment by ghost** [comment]
I have the same problem but using a GTX 980, so shouldn't be a memory issue here.

Same as above - dl most recent version, opened .exe, synced fine, but when i hit start mining it doesn't find my gpu and says "no open CL device found"..

Also have the i5 3750k cpu, windows 7 sp1

**Comment by professor-cowboy** [comment]
Having similar issues. Can't use ethminer either. Have an AMD Firepro w7100. Definitely has enough memory.

**Comment by LianaHus** [comment]
currently only release version uses GPU mining

**Comment by LianaHus** [comment]
if the memory is the problem you should get an appropriate log massage, which I suppose is not a case. Could you please drop a log here?

**Comment by LianaHus** [comment]
AMD Firepro w7100 has 8GB memory,  GTX 980 - 4GB.

**Comment by professor-cowboy** [comment]
I wrote on the linked thread about a workaround incase anyone is interested. 
https://github.com/ethereum/webthree-umbrella/issues/342

**Comment by ghost** [comment]
@misternils thanks for this, haven't been able to find a workaround anywhere else!

sry if this is a noob question, but how do i input "--opencl-platform 1" into AlethOne? do i have to download geth?

**Comment by bumski** [comment]
@misternils Agreed, could you explain how you input this?  Usually I just fire up Alethone shortcut from the folder.

**Comment by tdashmike** [comment]
@cjdew You need to input that from the command line.

**Comment by bobsummerwill** [comment]
Closed issue, because [AlethZero is no longer supported](https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/), so this issue will never be addressed.
