### ISSUE TITLE
AlethOne: add "syncing" label on "Start mining" button for Solo state while syncing

### ISSUE THREAD

**Issue by LianaHus** [ethereum/alethzero#148]

**Comment by LianaHus** [comment]
and disable it

**Comment by chriseth** [comment]
Please do not create new issues in this repository, rather create them in webthree-umbrella

**Comment by bobsummerwill** [comment]
Closed issue, because [AlethZero is no longer supported](https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/), so this issue will never be addressed.
