### ISSUE TITLE
Migration path forward

### ISSUE THREAD

**Issue by alper** [ethereum/alethzero#167]
I have a (thankfully) trivial amount of ether in AlethZero. What is the suggested way I move forward from here into Wallet?

After installing Wallet the amount showed up there once but then not anymore.

**Comment by chriseth** [comment]
If you can, please create a new account and just transfer the ether. If you want to keep the address: We are still working on migrating the wallet files, sorry.

**Comment by alper** [comment]
I'm trying but my transaction won't go through because AlethZero crashes and fills my disk when trying to sync the chain.

**Update:** I see that there is a new version of cpp-ethereum out, so I'll install that and try again.

**Comment by alper** [comment]
Ok. AlethZero makes some progress updating the blockchain but then crashes repeatedly.

**Comment by chriseth** [comment]
I tried again just copying the key over to geth's key directory and it seems to work. You might have to edit the file and change `Crypto` to `crypto`. Please try!

**Comment by alper** [comment]
I don't understand this:
- Do I need geth as well? I have Ethereum Wallet installed.
- What key do I move to where?
- Why do these apps hide which files they use?

**Comment by chriseth** [comment]
I think this issue would be better resolved in e.g. gitter.im/ethereum/cpp-ethereum or gitter.im/ethereum/go-ethereum than in this issue tracker.

Ethereum wallet comes with geth included. The location of the files you have to copy depend on your operation system.

**Comment by bobsummerwill** [comment]
Hey, @alper,

Please come and chat on https://gitter.im/ethereum/cpp-ethereum if you still want to work through this process.   Sorry for the pain.
