### ISSUE TITLE
Turning GPU mining off do not free GPU buffers

### ISSUE THREAD

**Issue by chfast** [ethereum/alethzero#41]
Please check if ethash_cl_miner instance kept by EthashGPUMiner is destroyed after GPU is turned off. In the destructor GPU resources should be freed.

Reproduce path is: Start AZ, start GPU mining, stop GPU mining, start ethminer with GPU mining (AZ still running). ethminer crashes with Nvidia drivers...

**Comment by chriseth** [comment]
Closing, since this is an edge case and in the future, mining should be done in its own module.
