### ISSUE TITLE
AletthOne crashes after switching mining type from local to pool

### ISSUE THREAD

**Issue by rodiazet** [ethereum/alethzero#58]
1. Turn on mining (CPU) in local address by clicking CPU button
2. Turn off mining by clicking Off button.
3. Try to change mining type to Pool.
4. It crashes every time.

Architecture:
Windows 10 x64.
AlethOne taken from Ethereum 0.9.91 (https://www.dropbox.com/s/33516v8qp8fpciv/Ethereum-0.9.91-win64.exe?dl=0)

**Comment by chriseth** [comment]
Is this still happening?
