### ISSUE TITLE
problem with initialising plugin PrivateChain

### ISSUE THREAD

**Issue by LianaHus** [ethereum/alethzero#64]
ℹ  06:19:18 PM|alethzero  Reading /home/liana/.web3/keys/d0ec3f0f-0033-71ad-1cc2-15bb12cdd33f.json
  ℹ  06:19:18 PM|alethzero  Reading /home/liana/.web3/keys/767519b5-e58d-dea6-cffd-9396bd91a2b8.json
  ℹ  06:19:18 PM|alethzero  Reading /home/liana/.web3/keys/7219a046-da6d-5f58-34b8-a41ff2fc6d9c.json
State root: d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544
Block Hash: d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
Block RLP: [ [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x1DCC4DE8DEC75D7AAB85B567B6CCD41AD312451B948A7413F0A142FD40D49347, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0xD7F8974FB5AC78D9AC099B9AD5018BEDC2CE0A72DAD1827A1709DA30580F0544, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x400000000, 0x0, 0x1388, 0x0, 0x0, 0x11BBE8DB4E347B4E8C937C1C8370E4B5ED33ADB3DB69CBDB7A38E1E50B1B82FA, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", "\x00\x00\x00\x00\x00\x00\x00B" ], [ ], [ ] ]
Block Hex: f90219f90214a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a0d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000850400000000808213888080a011bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82faa00000000000000000000000000000000000000000000000000000000000000000880000000000000042c0c0
eth Network protocol version: 61
Client database version: 12041
⧎ ℹ  06:19:39 PM|alethzero  Id: ##6af2a018…
  ℹ  06:19:44 PM|alethzero  Opened blockchain DB. Latest: #d4e56740… (rebuild not needed)
  ℹ  06:19:44 PM|alethzero  Opened state DB.
 ⚡   06:19:49 PM|alethzero  void dev::eth::Client::init(dev::p2p::Host*, const string&, dev::WithExisting, dev::u256) 4716 ms
  ◇  06:19:49 PM|alethzero  newBlock watch ID: 0
  ◇  06:19:49 PM|alethzero  Initialising plugin: OtherAccounts
  ◇  06:19:49 PM|alethzero  Initialising plugin: Whisper
  ◇  06:19:49 PM|alethzero  Initialising plugin: LogPanel
  ◇  06:19:49 PM|alethzero  Initialising plugin: Browser
  ◇  06:19:49 PM|alethzero  Initialising plugin: BrainWallet
  ◇  06:19:49 PM|alethzero  Initialising plugin: WhisperPeers
  ◇  06:19:49 PM|alethzero  Initialising plugin: InjectTransactions
  ◇  06:19:49 PM|alethzero  Initialising plugin: Cors
  ◇  06:19:49 PM|alethzero  Initialising plugin: Transact
  ◇  06:19:49 PM|alethzero  Initialising plugin: GasPricing
  ◇  06:19:49 PM|alethzero  Initialising plugin: OurAccounts
  ◇  06:19:49 PM|alethzero  Initialising plugin: SpecialBlockChain
  ◇  06:19:49 PM|alethzero  Initialising plugin: EVMJIT
  ◇  06:19:49 PM|alethzero  Initialising plugin: NameRegNamer
  ◇  06:19:49 PM|alethzero  Initialising plugin: PrivateChain
 ⚡   06:19:50 PM|alethzero  Stop worker 879 ms
  ℹ  06:19:50 PM|alethzero  Closing blockchain DB
  ℹ  06:19:55 PM|alethzero  Opened blockchain DB. Latest: #ad570329… (rebuild not needed)
  ℹ  06:19:55 PM|alethzero  Opened state DB.
 ⚡   06:20:01 PM|eth  Worker stopping 10781 ms
 ⚡   06:20:02 PM|alethzero  Stop worker 992 ms
  ℹ  06:20:02 PM|alethzero  Closing blockchain DB
  ℹ  06:20:07 PM|alethzero  Opened blockchain DB. Latest: #d4e56740… (rebuild not needed)
  ℹ  06:20:07 PM|alethzero  Opened state DB.
 ⚡   06:20:08 PM|eth  Worker stopping 6084 ms
 ⚡   06:20:09 PM|alethzero  Stop worker 994 ms
  ℹ  06:20:09 PM|alethzero  Closing blockchain DB
  ℹ  06:20:14 PM|alethzero  Opened blockchain DB. Latest: #ad570329… (rebuild not needed)
  ℹ  06:20:14 PM|alethzero  Opened state DB.
 ⚡   06:20:15 PM|eth  Worker stopping 6164 ms
 ⚡   06:20:16 PM|alethzero  Stop worker 992 ms
  ℹ  06:20:16 PM|alethzero  Closing blockchain DB
  ℹ  06:20:21 PM|alethzero  Opened blockchain DB. Latest: #d4e56740… (rebuild not needed)
  ℹ  06:20:21 PM|alethzero  Opened state DB.
 ⚡   06:20:22 PM|eth  Worker stopping 5922 ms
 ⚡   06:20:23 PM|alethzero  Stop worker 989 ms
  ℹ  06:20:23 PM|alethzero  Closing blockchain DB
  ℹ  06:20:28 PM|alethzero  Opened blockchain DB. Latest: #ad570329… (rebuild not needed)
  ℹ  06:20:28 PM|alethzero  Opened state DB.
 ⚡   06:20:29 PM|eth  Worker stopping 6203 ms
 ⚡   06:20:30 PM|alethzero  Stop worker 990 ms
  ℹ  06:20:30 PM|alethzero  Closing blockchain DB
  ℹ  06:20:35 PM|alethzero  Opened blockchain DB. Latest: #d4e56740… (rebuild not needed)
  ℹ  06:20:35 PM|alethzero  Opened state DB.
 ⚡   06:20:36 PM|eth  Worker stopping 6143 ms
 ⚡   06:20:37 PM|alethzero  Stop worker 994 ms
  ℹ  06:20:37 PM|alethzero  Closing blockchain DB

---

and so on

**Comment by martincyprus** [comment]
Any progress on this? I just pulled latest from develop branch and still the same thing, some people have reported things worked when deleting the alethzero.conf and more drastically modifying 
alethzero/plugins/blockchain/PrivateChain.cpp

and commenting out: 
        // Prep UI bits.
        zero()->allStop(); 

and 
       // Rejig UI bits.
        zero()->carryOn();

though neither worked for me..  if i commented out the  zero()->carryOn(); it doesn't completely hang the client anymore.. but cant mine.. and trying to comment out the one above I had no more success..

I wanted to get into some dapp development and following some tutorials but kind of hard when I cant run a private chain and mine it to make some gas to do some testing..

thanks for any assistance..

**Comment by arkpar** [comment]
Fixed in develop
@martincyprus consider using `--morden` command line flag

**Comment by martincyprus** [comment]
@arkpar took a while for me to get around to trying again.. been trying now for a bit and still no luck.. this is what I'm doing..
this is on ubuntu 14.04 fully updated,I build the whole webthree project and have everything checked out on the latest develop branch.

1. I remove the ~/.ethereum folder and the .config/ethereum/alethzero.conf
2. go into the newly built director for alethzero and just do ./alethzero (with our without --morden does not appear to make a difference)
3. it starts up, wait for the GUI to come up, once its up, first thing i do is select: "config > "private chain" leave the default name click ok.. this then starts and goes forever, and the GUI is grayed out and unresponsive..

 ℹ  08:36:51 PM|alethzero  Opened blockchain DB. Latest: #a1cb1966… (rebuild not needed)
  ℹ  08:36:51 PM|alethzero  Opened state DB.
 ⚡   08:36:52 PM|eth  Worker stopping 1383 ms
  ◇  08:36:52 PM|alethzero  !!! Main: uninstalling watch 4
 ⚡   08:36:53 PM|alethzero  Stop worker 968 ms
  ℹ  08:36:53 PM|alethzero  Closing blockchain DB
  ℹ  08:36:53 PM|alethzero  Opened blockchain DB. Latest: #0cd786a2… (rebuild not needed)
  ℹ  08:36:54 PM|alethzero  Opened state DB.
 ⚡   08:36:55 PM|eth  Worker stopping 1383 ms
  ◇  08:36:55 PM|alethzero  !!! Main: uninstalling watch 4
 ⚡   08:36:56 PM|alethzero  Stop worker 965 ms
  ℹ  08:36:56 PM|alethzero  Closing blockchain DB
  ℹ  08:36:56 PM|alethzero  Opened blockchain DB. Latest: #a1cb1966… (rebuild not needed)
  ℹ  08:36:56 PM|alethzero  Opened state DB.
 ⚡   08:36:57 PM|eth  Worker stopping 1363 ms
  ◇  08:36:57 PM|alethzero  !!! Main: uninstalling watch 4
 ⚡   08:36:58 PM|alethzero  Stop worker 958 ms
  ℹ  08:36:58 PM|alethzero  Closing blockchain DB
  ℹ  08:36:58 PM|alethzero  Opened blockchain DB. Latest: #0cd786a2… (rebuild not needed)
  ℹ  08:36:58 PM|alethzero  Opened state DB.
 ⚡   08:36:59 PM|eth  Worker stopping 1343 ms
  ◇  08:36:59 PM|alethzero  !!! Main: uninstalling watch 4
 ⚡   08:37:00 PM|alethzero  Stop worker 937 ms
  ℹ  08:37:00 PM|alethzero  Closing blockchain DB
  ℹ  08:37:01 PM|alethzero  Opened blockchain DB. Latest: #a1cb1966… (rebuild not needed)
  ℹ  08:37:01 PM|alethzero  Opened state DB.
 ⚡   08:37:02 PM|eth  Worker stopping 1363 ms

possible I dont know how to use it properly but I'm just going by the tutorial that told me to do this.. :)

**Comment by martincyprus** [comment]
@arkpar took a while for me to get around to trying again.. been trying now for a bit and still no luck.. this is what I'm doing..
this is on ubuntu 14.04 fully updated,I build the whole webthree project and have everything checked out on the latest develop branch.

I remove the ~/.ethereum and ~/.web3 folders and the .config/ethereum/alethzero.conf
go into the newly built director for alethzero and just do ./alethzero (with our without --morden does not appear to make a difference)
it starts up, wait for the GUI to come up, once its up, first thing i do is select: "config > "private chain" leave the default name click ok.. this then starts and goes forever, and the GUI is grayed out and unresponsive..

ℹ 08:36:51 PM|alethzero Opened blockchain DB. Latest: #a1cb1966… (rebuild not needed)
ℹ 08:36:51 PM|alethzero Opened state DB.
⚡ 08:36:52 PM|eth Worker stopping 1383 ms
◇ 08:36:52 PM|alethzero !!! Main: uninstalling watch 4
⚡ 08:36:53 PM|alethzero Stop worker 968 ms
ℹ 08:36:53 PM|alethzero Closing blockchain DB
ℹ 08:36:53 PM|alethzero Opened blockchain DB. Latest: #0cd786a2… (rebuild not needed)
ℹ 08:36:54 PM|alethzero Opened state DB.
⚡ 08:36:55 PM|eth Worker stopping 1383 ms
◇ 08:36:55 PM|alethzero !!! Main: uninstalling watch 4
⚡ 08:36:56 PM|alethzero Stop worker 965 ms
ℹ 08:36:56 PM|alethzero Closing blockchain DB
ℹ 08:36:56 PM|alethzero Opened blockchain DB. Latest: #a1cb1966… (rebuild not needed)
ℹ 08:36:56 PM|alethzero Opened state DB.
⚡ 08:36:57 PM|eth Worker stopping 1363 ms
◇ 08:36:57 PM|alethzero !!! Main: uninstalling watch 4
⚡ 08:36:58 PM|alethzero Stop worker 958 ms
ℹ 08:36:58 PM|alethzero Closing blockchain DB
ℹ 08:36:58 PM|alethzero Opened blockchain DB. Latest: #0cd786a2… (rebuild not needed)
ℹ 08:36:58 PM|alethzero Opened state DB.
⚡ 08:36:59 PM|eth Worker stopping 1343 ms
◇ 08:36:59 PM|alethzero !!! Main: uninstalling watch 4
⚡ 08:37:00 PM|alethzero Stop worker 937 ms
ℹ 08:37:00 PM|alethzero Closing blockchain DB
ℹ 08:37:01 PM|alethzero Opened blockchain DB. Latest: #a1cb1966… (rebuild not needed)
ℹ 08:37:01 PM|alethzero Opened state DB.
⚡ 08:37:02 PM|eth Worker stopping 1363 ms

possible I dont know how to use it properly but I'm just going by the tutorial that told me to do this.. :)
