### ISSUE TITLE
eth_sendTransaction returns 0 for all transactions

### ISSUE THREAD

**Issue by chriseth** [ethereum/alethzero#82]
`eth_sendTransaction` should return the tx hash of the transaction. As the tx hash of course depends on the signature, but the jsonrpc response does not wait for the user to confirm the tx and just returns `0x0` - but it would be perfectly fine for the http request to block until the user confirmed.
Furthermore, even in the case that the tx does not have to be confirmed, signing the transaction could be a blocking operation.
It would be great if we could tell in advance whether signing or confirmation would block or not.

**Comment by bobsummerwill** [comment]
Closed issue, because [AlethZero is no longer supported](https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/), so this issue will never be addressed.
