### ISSUE TITLE
Introduce the notion of invalid internal OOGs for use when calculating gas

### ISSUE THREAD

**Issue by gavofyork** [ethereum/alethzero#9]
Was https://github.com/ethereum/cpp-ethereum/issues/2859

**Comment by chriseth** [comment]
If out-of-gas happens in a (GAS - x)-CALLed contract, but is not propagated to the caller, Alethzero will reduce the gas available to the CALLed contract to a minimum.
I'm not sure how this could be detected and fixed, though.

**Comment by gavofyork** [comment]
simple answer: it cannot. there are two operating modes, both valid, one with lower gas requirements. the internal OOG will be correctly identified as the lowest valid gas usage for the top-level call.

solution: redefine what "valid" means (i.e. identify troublesome itnernal OOGs). this will require substantial high-level additions to contract semantics.

easier solution: propagate internal OOGs to highest level in all problematic circumstances.

**Comment by bobsummerwill** [comment]
Closed issue, because [AlethZero is no longer supported](https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/), so this issue will never be addressed.
