### ISSUE TITLE
AlethZero has some display issues on 4k monitors

### ISSUE THREAD

**Issue by ThePiachu** [ethereum/alethzero#97]
I recently tried using AlethZero on my 4k+2x1080p Windows 10 computer and it has some issues. Either the top or the bottom of the window is not visible and there is no way to resize it vertically in windowed mode. It might have something to do with UI scaling for the 4k display as well.

![image](https://cloud.githubusercontent.com/assets/964559/10920572/a69de4ac-8225-11e5-8c52-554c88811071.png)

**Comment by chriseth** [comment]
Closing as support for alethzero for end users is dropped.
